routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Route::get('/search', 'HomeController@search')->name('search');

Route::put('efemerides/{efemeride}/hit', 'EfemerideController@hit')->name('efemerides.hit');
Route::get('efemerides/populares', 'EfemerideController@populares')->name('efemerides.populares');
Route::resource('efemerides', 'EfemerideController')->only([
    'index', 'show'
]);

Route::put('terminos/{termino}/hit', 'TerminoController@hit')->name('terminos.hit');
Route::get('terminos/populares', 'TerminoController@populares')->name('terminos.popular');
Route::resource('terminos', 'TerminoController')->only([
    'index', 'show'
]);

Auth::routes(['register' => false]);

Route::group(
    [
        'prefix' => 'admin',
        'middleware' => ['auth', 'can:accessAdminpanel'],
        'as' => 'admin.',
        'namespace' => 'Admin',
    ],
    function () {

        Route::get('/', 'DashboardController@index')->name('dashboard');
        Route::post('/files', 'DashboardController@storeFile')
            ->name('files');
        Route::resources([
            'efemerides' => 'EfemerideController',
            'terminos' => 'TerminoController',
        ]);
    }
);

resources/views/admin/index.blade.php
@extends('layouts.dashboard')
@section('content')

<section class="section">
  <div class="box has-text-centered">
    <h1 class="title ">Glosario</h1>
    <div class="columns is-vcentered">
      <div class="column">
        <p class="is-size-1 has-text-primary">
          {{ $terminos_count ?? '0' }}
        </p>
        <p>
          Términos en el glosario
        </p>
      </div>
      <div class="is-divider-vertical"></div>
      <div class="column">
        <p class="is-size-2">
          <a
          class="has-text-primary"
          href="{{ route('admin.terminos.create') }}">
            <fa-icon icon="plus">PLUS</fa-icon>
          </a>
        </p>
        <p>
          Término
        </p>
      </div>
    </div>
    <h1 class="title has-text-centered">Efemérides</h1>
    <div class="columns is-vcentered">
      <div class="column">
        <p class="is-size-1 has-text-primary">
          {{ $efemerides_count ?? '0' }}
        </p>
        <p>
          Efemérides
        </p>
      </div>
      <div class="is-divider-vertical"></div>
      <div class="column">
        <p class="is-size-2 has-text-primary">
          <a
          class="has-text-primary"
          href="{{ route('admin.efemerides.create') }}">
            <fa-icon icon="plus">PLUS</fa-icon>
          </a>
        </p>
        <p>
          Efeméride
        </p>
      </div>
    </div>
  </div>
</section>

@endsection