routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Route::get('/search', 'HomeController@search')->name('search');

Route::put('efemerides/{efemeride}/hit', 'EfemerideController@hit')->name('efemerides.hit');
Route::get('efemerides/populares', 'EfemerideController@populares')->name('efemerides.populares');
Route::resource('efemerides', 'EfemerideController')->only([
    'index', 'show'
]);

Route::put('terminos/{termino}/hit', 'TerminoController@hit')->name('terminos.hit');
Route::get('terminos/populares', 'TerminoController@populares')->name('terminos.popular');
Route::resource('terminos', 'TerminoController')->only([
    'index', 'show'
]);

Auth::routes(['register' => false]);

Route::group(
    [
        'prefix' => 'admin',
        'middleware' => ['auth', 'can:accessAdminpanel'],
        'as' => 'admin.',
        'namespace' => 'Admin',
    ],
    function () {

        Route::get('/', 'DashboardController@index')->name('dashboard');
        Route::post('/files', 'DashboardController@storeFile')
            ->name('files');
        Route::resources([
            'efemerides' => 'EfemerideController',
            'terminos' => 'TerminoController',
        ]);
    }
);

resources/views/layouts/auth.blade.php
<!DOCTYPE html>
<html lang="es">
  <head>
    <title>Glosario para la igualdad</title>
    <meta name="description" content="Iniciar sesión">
    <meta name="robots" content="noindex,nofollow">
    @include('layouts.shared.head')
    <link href="{{ asset('css/layouts/auth.css') }}" rel="stylesheet">

  </head>
  <body class="layout-default">
    <div id="__app" class="layout-auth">
      @component('components.alerts', ['fixed' => true])
      @endcomponent()
      <div class="hero is-fullheight is-grey">
        <div class="hero-body">
          @yield('content')
        </div>
        <div class="hero-foot">
          @component('components.footer')
        </div>
      </div>
      @endcomponent()
    </div>
    <!-- Scripts -->
    @yield('scripts')
  </body>
</html>

resources/views/layouts/dashboard.blade.php
<!DOCTYPE html>
<html lang="es">
  <head>
    <title>Glosario para la igualdad - Dashboard</title>
    <meta name="description" content="Panel de administración">
    <meta name="robots" content="noindex,nofollow">
    @include('layouts.shared.head')
    <link href="{{ asset('css/layouts/dashboard.css') }}" rel="stylesheet">
  </head>
  <body class="layout-default">
    <div id="__app" class="layout-dashboard">
      @component('components.sidemenu', ['class' => 'layout-dashboard'])
      @endcomponent()
      <header class="layout-dashboard__header dash-header ">
        @if (Auth::guest())
          <a class="dash-header__link" href="{{ route('login') }}">Login</a>
          <a class="dash-header__link" href="{{ route('register') }}">Register</a>
        @else
          <a class="dash-header__link" href="{{ route('home') }}">Hola {{ Auth::user()->name }}</a>
          <a class="dash-header__link" href="{{ route('logout') }}"
            onclick="event.preventDefault();document.getElementById('logout-form').submit();">
            Salir
          </a>
          <form id="logout-form" action="{{ route('logout') }}" method="POST"
                style="display: none;">
              {{ csrf_field() }}
          </form>
        @endif
      </header>
      <main class="layout-dashboard__content">
        @yield('content')
      </main>
      @component('components.footer')
      @endcomponent()
    </div>
    <!-- Scripts -->
    <script src="{{ asset('js/manifest.js') }}"></script>
    <script src="{{ asset('js/vendor.js') }}"></script>
    <script src="{{ asset('js/dashboard.js') }}"></script>
    <script src="{{ asset('js/app.js') }}"></script>
  </body>
</html>

resources/views/layouts/default.blade.php
<!DOCTYPE html>
<html lang="es">
  <head>
    {!! SEO::generate() !!}
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-134449214-1');
    </script>
    @include('layouts.shared.head')
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-134449214-1"></script>
    <link href="{{ asset('css/layouts/default.css') }}" rel="stylesheet">
  </head>
  <body class="layout-default body {{bodyClass()}}">
  <div id="__app" class="layout-default app">
      @include('components.alerts', ['fixed' => true])
      @include('components.header')
      @yield('content')
    </div>
    @include('components.footer')
    {{-- Auth --}}
    @if (!Auth::guest())
      <form id="logout-form" action="{{ route('logout') }}" method="POST" class="meta-admin">
        <div class="field has-addons">
          <div class="control">
            <a class="button is-small is-static">Administrador: </a>
          </div>
          <div class="control">
            <a href="{{ route('admin.dashboard') }}" class="button is-small is-info">Ir al panel</a>
          </div>
          <div class="control">
            <a href="{{ route('logout') }}"
              class="button is-small is-danger"
              onclick="event.preventDefault();document.getElementById('logout-form').submit();">
              Cerrar sesión
            </a>
          </div>
        </div>
        {{ csrf_field() }}
      </form>
    @endif
    <!-- Scripts -->
    <script>
      var SERVER_DATE = new Date("{{now()}}")
      var CLIENT_DATE = new Date()
      if (CLIENT_DATE.toDateString() !== SERVER_DATE.toDateString()) {
        console.warn('El servidor y el cliente no entienden la misma fecha')
      }
    </script>
    <script src="{{ asset('js/manifest.js') }}"></script>
    <script src="{{ asset('js/vendor.js') }}"></script>
    <script src="{{ asset('js/public.js') }}"></script>
    <script src="{{ asset('js/app.js') }}"></script>
    @yield('scripts')

  </body>
</html>